apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: healthcare-k8s
type: Opaque
stringData:
  admin-username: admin
  admin-password: admin
  db-username: root
  db-password: Ashutosh@2000