apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: patient-service-svc
  namespace: healthcare-k8s
spec:
  selector:
    app: patient-service-k8s-deploy
  ports:
    - protocol: "TCP"
      port: 3031 # The port that the service is running on in the cluster
      targetPort: 3031 # The port exposed by the service
  type: NodePort # type of the service.
